import { OrderItem } from "../../order_item/entity";

export enum PaymentStatus {
    PENDING = 'pending',
    FAILED = 'failed',
    SUCCESS = 'success'
}

export enum PaymentMethod {
    UPI = 'upi',
    CARD = 'card',
    NET_BANKING = 'net_banking',
    COD = 'cod'
}

export class Payment {
    id?: string;
    gatewayOrderId?: string; // ID generated by Razorpay/Stripe/etc.
    referenceId?: string; // Transaction reference from the bank
    status?: PaymentStatus;
    paidAmount?: number;
    // Added:
    paymentMethod?: PaymentMethod; // Crucial for accounting and refunds
    orderItems?: OrderItem[]
}